# Generated by Django 5.0.2 on 2024-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
